<?php

function beagleBoard_add_local_field_groups()
{
    // Accordion
    acf_add_local_field_group(array(
        'key' => 'group_60a7e03d6a88b',
        'title' => 'Accordion',
        'fields' => array(
            array(
                'key' => 'field_60a7e084c22f9',
                'label' => 'Accordion Repeater',
                'name' => 'accordion_repeater',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_60a7e109c22fa',
                        'label' => 'Accordion Title',
                        'name' => 'accordion_title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_60a7e11ec22fb',
                        'label' => 'Accordion Description',
                        'name' => 'accordion_description',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'basic',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'views/template-accordion.blade.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => true,
        'modified' => 1621631605,
    ));

    // Distros
    acf_add_local_field_group(array(
        'key' => 'group_606d1eec66b4c',
        'title' => 'Distros',
        'fields' => array(
            array(
                'key' => 'field_6080c217c64c7',
                'label' => 'Master URL',
                'name' => 'master-url',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'Master Image Source URL',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 1,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_606d20c394dc2',
                'label' => 'Download Link',
                'name' => 'download_link',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 1,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_606d1f0234163',
                'label' => 'Checksum',
                'name' => 'checksum',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'Checksum',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 1,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_6085c66cee8f6',
                'label' => 'Version',
                'name' => 'distro-version',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => 5,
                'show_column' => 1,
                'show_column_sortable' => 1,
                'show_column_weight' => 1000,
                'allow_quickedit' => 1,
                'allow_bulkedit' => 1,
            ),
            array(
                'key' => 'field_6085c6bdee8f7',
                'label' => 'bmap Master URL',
                'name' => 'bmap-master-url',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 1,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_6085c725ee8f8',
                'label' => 'bmap URL',
                'name' => 'bmap-url',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'This value will be updated automatically when the file is uploaded.',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_607c681ee57fa',
                'label' => 'Include in Latest Images',
                'name' => 'latest',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_6085c7d7ee8f9',
                'label' => 'Date published',
                'name' => 'distro-published-date',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'm/d/Y',
                'return_format' => 'm/d/Y',
                'first_day' => 0,
                'show_column' => 1,
                'show_column_sortable' => 1,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 1,
            ),
            array(
                'key' => 'field_6085c7d7ee8fa',
                'label' => 'Queue for Upload',
                'name' => 'queue_upload',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_642e3377aaf70',
                'label' => 'Image Filename',
                'name' => 'image_filename',
                'type' => 'text',
                'instructions' => 'Must be a valid filename, no spaces or special characters',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_6085c7d7ee8fa',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'distros',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'field',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => true,
    ));

    // Hero Ad
    acf_add_local_field_group(array(
        'key' => 'group_6061e9509222c',
        'title' => 'Hero Ad',
        'fields' => array(
            array(
                'key' => 'field_6061e95af5f5a',
                'label' => '',
                'name' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '3523',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => true,
    ));

    // Icon Card

        acf_add_local_field_group(array(
            'key' => 'group_6090cc197dc95',
            'title' => 'Icon Card',
            'fields' => array(
                array(
                    'show_column_filter' => false,
                    'allow_bulkedit' => false,
                    'allow_quickedit' => false,
                    'show_column' => false,
                    'show_column_weight' => 1000,
                    'show_column_sortable' => false,
                    'key' => 'field_60933cf781cd5',
                    'label' => 'Card Title',
                    'name' => 'card_title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'show_column_filter' => false,
                    'allow_bulkedit' => false,
                    'allow_quickedit' => false,
                    'show_column' => false,
                    'show_column_weight' => 1000,
                    'show_column_sortable' => false,
                    'key' => 'field_60920dd38cc87',
                    'label' => 'Card Image',
                    'name' => 'card_image',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'show_column_filter' => false,
                    'allow_bulkedit' => false,
                    'allow_quickedit' => false,
                    'show_column' => false,
                    'show_column_weight' => 1000,
                    'show_column_sortable' => false,
                    'key' => 'field_6090d03ffcb5c',
                    'label' => 'Card Description',
                    'name' => 'card_description',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                ),
                array(
                    'show_column_filter' => false,
                    'allow_bulkedit' => false,
                    'allow_quickedit' => false,
                    'show_column' => 0,
                    'show_column_weight' => 1000,
                    'show_column_sortable' => false,
                    'key' => 'field_60933cb96b7df',
                    'label' => 'Page Link',
                    'name' => 'page_link',
                    'aria-label' => '',
                    'type' => 'page_link',
                    'instructions' => 'If a page link is not selected the card will not have a link on the entire card.',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_60934ebd24202',
                                'operator' => '==empty',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => '',
                    'post_status' => '',
                    'taxonomy' => '',
                    'allow_archives' => 1,
                    'multiple' => 0,
                    'allow_null' => 0,
                ),
                array(
                    'show_column_filter' => false,
                    'allow_bulkedit' => false,
                    'allow_quickedit' => false,
                    'show_column' => false,
                    'show_column_weight' => 1000,
                    'show_column_sortable' => false,
                    'key' => 'field_60934ebd24202',
                    'label' => 'External Link',
                    'name' => 'external_link',
                    'aria-label' => '',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'block',
                        'operator' => '==',
                        'value' => 'acf/icon-card',
                    ),
                ),
                array(
                    array(
                        'param' => 'block',
                        'operator' => '==',
                        'value' => 'acf/photo-card',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'side',
            'style' => 'seamless',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => true,
        ));




    // Products
    acf_add_local_field_group(array(
        'key' => 'group_60236db7b326c',
        'title' => 'Products',
        'fields' => array(
            array(
                'key' => 'field_60236e28cac7f',
                'label' => 'Secondary Image',
                'name' => 'secondary_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '100',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'preview_size' => 'medium_large',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_6418debf2d876',
                'label' => 'Product video',
                'name' => 'product_video',
                'type' => 'oembed',
                'instructions' => 'Will show video or product photo but not both',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'width' => '',
                'height' => '',
            ),
            array(
                'key' => 'field_60236f7d7b883',
                'label' => 'Processor',
                'name' => 'processor',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
            ),
            array(
                'key' => 'field_60236fe5d447f',
                'label' => 'Features',
                'name' => 'features',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
            ),
            array(
                'key' => 'field_60286c964b97b',
                'label' => 'Resources',
                'name' => 'resources',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
            ),
            array(
                'key' => 'field_602ec996fd995',
                'label' => 'Distributors',
                'name' => 'distributors',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_602ec9c6fd996',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_602ec9c6fd996',
                        'label' => 'Distributor',
                        'name' => 'distributor',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'arrow.svg' => 'Arrow',
                            'digikey.png' => 'Digi-Key',
                            'element14.png' => 'Element14',
                            'farnell.svg' => 'Farnell',
                            'san-cloud.png' => 'San Cloud',
                            'mouser.png' => 'Mouser',
                            'newark.svg' => 'Newark',
                            'rs-logo.svg' => 'RS',
                            'seed-studio.svg' => 'SeedStudio',
                            'renaissance-robotics.png' => 'Renaissance Robotics',
                        ),
                        'default_value' => 'arrow.svg',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 1,
                        'ajax' => 1,
                        'return_format' => 'value',
                        'show_column' => 0,
                        'show_column_sortable' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_602ed9c00db99',
                        'label' => 'Product URL',
                        'name' => 'product_url',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_605023525a7b3',
                'label' => 'Documentation',
                'name' => 'documentation',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'allow_backendsearch' => 0,
                'show_column_filter' => false,
                'allow_bulkedit' => 0,
                'allow_quickedit' => 0,
                'show_column' => 0,
                'show_column_weight' => 1000,
                'show_column_sortable' => false,
                'key' => 'field_65f5e79596d73',
                'label' => 'Discourse URL',
                'name' => 'discourse_url',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'https://forum.beagleboard.org/',
                'placeholder' => '',
            ),
            array(
                'allow_backendsearch' => 0,
                'show_column_filter' => false,
                'allow_bulkedit' => 0,
                'allow_quickedit' => 0,
                'show_column' => 0,
                'show_column_weight' => 1000,
                'show_column_sortable' => false,
                'key' => 'field_65f5e8dec1791',
                'label' => 'OpenBeagle Design URL',
                'name' => 'openbeagle_design_url',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'https://openbeagle.org/',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_606d20c395432',
                'label' => 'Quick Start URL',
                'name' => 'quickstart_url',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 1,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_6060c88396154',
                'label' => 'Background Style',
                'name' => 'background_style',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'beagle-v-bg' => 'Beagle V',
                    'bb-blue-bg' => 'BeagleBone Blue',
                    'bb-black-bg' => 'BeagleBone Black',
                    'bb-ai-bg' => 'BeagleBone AI',
                    'pocket-beagle-bg' => 'PocketBeagle',
                    'bb-green-bg' => 'BeagleBone Green',
                ),
                'default_value' => 'bb-black-bg',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_606a1a63ddd4e',
                'label' => 'Product Image Max Width',
                'name' => 'product_image_max_width',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'thumbnail' => 'Thumbnail (150px x 150px max)',
                    'medium' => 'Medium (300px x 300px max)',
                    'medium_large' => 'Medium-large (default 768px x 0px max)',
                    'large' => 'Large (default 1024px x 1024px max)',
                    'medium-custom' => 'Medium Custom (default 500px x    500px max)',
                    'small-custom' => 'Small Custom (default 400px)',
                ),
                'default_value' => 'medium',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_60905b153a10e',
                'label' => 'Beagleboard Compatible',
                'name' => 'beagleboard_compatible',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'product',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => true,
        'modified' => 1622378505,
    ));

    // Projects
    acf_add_local_field_group(array(
        'key' => 'group_602d69f9ae6f5',
        'title' => 'Projects',
        'fields' => array(
            array(
                'key' => 'field_602d6a22f5e4f',
                'label' => 'External Url',
                'name' => 'external_url',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'Enter External URL',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'project',
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'book',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => true,
    ));

    // Source
    acf_add_local_field_group(array(
        'key' => 'group_604e99f5bef2b',
        'title' => 'Source',
        'fields' => array(
            array(
                'key' => 'field_604e9a0e49e21',
                'label' => 'Origin',
                'name' => 'origin',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'project',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => true,
    ));

    // Stepper
    acf_add_local_field_group(array(
        'key' => 'group_60a9b3a0ca1c6',
        'title' => 'Stepper',
        'fields' => array(
            array(
                'key' => 'field_60a9b3a0d2ccf',
                'label' => 'Stepper Repeater',
                'name' => 'stepper_repeater',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_60a9b3a0d6b0d',
                        'label' => 'Stepper Title',
                        'name' => 'stepper_title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'show_column' => 0,
                        'show_column_sortable' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                    array(
                        'key' => 'field_60a9b3a0d6b4e',
                        'label' => 'Stepper Description',
                        'name' => 'stepper_description',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'basic',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'views/template-stepper.blade.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => true,
    ));

    // Landing Page
    acf_add_local_field_group(array(
        'key' => 'group_653064eab11f3',
        'title' => 'Landing Page',
        'fields' => array(
            array(
                'show_column_filter' => false,
                'allow_bulkedit' => 0,
                'allow_quickedit' => 0,
                'show_column' => 0,
                'show_column_weight' => 1000,
                'show_column_sortable' => false,
                'key' => 'field_653064eb54f57',
                'label' => 'Slider Revolution Alias',
                'name' => 'rev_slider_alias',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'views/template-landing-page.blade.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => true,
    ));


    // Newsletter
    acf_add_local_field_group(array(
            'key' => 'group_65f8c6a9101b4',
            'title' => 'Newsletter',
            'fields' => array(
                array(
                    'key' => 'field_65f8c6a98dcb0',
                    'label' => 'Newsletter Embed',
                    'name' => 'newsletter_embed',
                    'aria-label' => '',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'post',
                    ),
                    array(
                        'param' => 'post_category',
                        'operator' => '==',
                        'value' => 'category:newsletter',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => true,
        ));
}
